kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ruby:3.2.1
    commands:
      - bundle exec rake
    volumes:
      - name: gem-cache
        path: /bundle

services:
  - name: redis
    image: redis:6.2.5
