kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ruby:3.2.1-slim-buster
    commands:
      - bundle install --path /bundle
      - sleep 15
      - bundle exec rake
    volumes:
      - name: gem-cache
        path: /bundle
    environment:
      REDIS_URL: redis://0.0.0.0:6379

services:
  - name: redis
    image: redis
