require:
  - standard
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

RSpec:
  Enabled: true # enable rubocop-rspec cops
